//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp3
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RemontKOEntities : DbContext
    {
        public RemontKOEntities()
            : base("name=RemontKOEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Klient> Klient { get; set; }
        public virtual DbSet<Klient_Servic> Klient_Servic { get; set; }
        public virtual DbSet<Polsovatel> Polsovatel { get; set; }
        public virtual DbSet<Rol> Rol { get; set; }
        public virtual DbSet<Servic> Servic { get; set; }
        public virtual DbSet<Sotrudnik> Sotrudnik { get; set; }
    }
}
